Components-UI
gabyse1/math-magicians pull request #2
Opened 2022-02-08 23:25 UTC by gabyse1

## Changes to the project
- Delete all unuseful files.
- Create *calculator components* in *Calculator.js* file.
- Add styles to components in *Calculator.css* file.
- Add *Calculator component* to *index.js file*.
- Add styles for basic *index.html* file.

2022-02-08 23:47 UTC, andersonlebon requested changes
## Hi @gabyse1 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 23:47 UTC, andersonlebon commented on src/index.js
> +    <Calculator />
- [ ] Nice job :clap:  on making the `calculator.js` a class-based component, however before rendering it here in `index.js` I think for better practice it should first pass in the main component(app.js). Kindly add the `app.js` file that should contain the App class-based component.

2022-02-09 00:17 UTC, gabyse1 commented on src/index.js
> +    <Calculator />
## Hello @andersonlebon
Thank you for your review.
I am going to work on it.

2022-02-09 00:25 UTC, Meltrust approved these changes
Hi @gabyse1, 

## Great job implementing the last reviewer's requirements.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 00:40 UTC, merged

2022-02-09 00:40 UTC, gabyse1 commented
> Hi @gabyse1,
> 
> ## Great job implementing the last reviewer's requirements.
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 00:54 UTC, gabyse1 commented
## Hello @Meltrust 
Thank you very much for your review.